#include "main.h"

#include <stdio.h>
#include <stdlib.h>
#include "images/fieldscore.h"
#include "images/drew.h"
#include "images/intro.h"
#include "images/pixlplayers.h"
#include "images/pixldefender.h"
#include "images/goal.h"
#include "images/w.h"
#include "images/l.h"

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  INTRO,
  SPLASH,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = SPLASH;
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    if (KEY_JUST_PRESSED(BUTTON_SELECT, previousButtons, currentButtons)) {state = INTRO;}


    switch (state) {
      case PLAY:
      waitForVBlank();
      drawFullScreenImageDMA(fieldscore);
      struct soccerplayer player; 
      player.xpos = 110; //starting position
      player.ypos = 125; //starting position
      player.width = 20; 
      player.height = 15;
      struct defender away; 
      away.xpos = 130; //starting position
      away.ypos = 55; //starting position
      away.width = 20; 
      away.height = 15; 
      struct ball gameball; 
      gameball.xpos = 117; 
      gameball.ypos = 120; 
      gameball.width = 5; 
      gameball.height = 5;  
      int gameLoop = 1;
      int decpos = randint(1,5);
      int dirLock = 0;
      int cycles = randint(20, 76); 
      int goals = 0; 
      int lives = 3;
      while (gameLoop) {
        currentButtons = BUTTONS; 
        if (KEY_JUST_PRESSED(BUTTON_SELECT, previousButtons, currentButtons)) {state = INTRO; gameLoop = 0;}
        waitForVBlank();
        drawImageDMA(player.ypos, player.xpos, player.width, player.height, pixlplayer);
        drawRectDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, CYAN);
        drawChar(146, 114, goals + '0', WHITE); 
        drawChar(146, 186, '0' + lives, WHITE);
        //Player movement and collisions
        if (KEY_JUST_PRESSED(BUTTON_DOWN, previousButtons, currentButtons) || KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (!((player.ypos >= 125) || (   (player.ypos + 15 == away.ypos) && ( (player.xpos + 20 >= away.xpos) && (away.xpos + 20 >= player.xpos) )   ) || (   (player.ypos + 15 == gameball.ypos) && ( (player.xpos + 20 >= gameball.xpos) && (gameball.xpos + gameball.width >= player.xpos) )   ))) {
            undrawImageDMA(player.ypos, player.xpos, player.width, player.height, fieldscore);
            player.ypos++;
            drawImageDMA(player.ypos, player.xpos, player.width, player.height, pixlplayer);
          }
        }
        if (KEY_JUST_PRESSED(BUTTON_LEFT, previousButtons, currentButtons) || KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (!((player.xpos <= 0) || (   (player.xpos - 20 == away.xpos) && ( (player.ypos + 15 >= away.ypos) && (away.ypos + 15 >= player.ypos) )   ) || (   (player.xpos - gameball.width == gameball.xpos) && ( (player.ypos + 15 >= gameball.ypos) && (gameball.ypos + gameball.height >= player.ypos) )   ))) { 
            undrawImageDMA(player.ypos, player.xpos, player.width, player.height, fieldscore);
            player.xpos--;
            drawImageDMA(player.ypos, player.xpos, player.width, player.height, pixlplayer);
          }
        }
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, previousButtons, currentButtons) || KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (!((player.xpos >= 220) || (   (player.xpos + 20 == away.xpos) && ( (player.ypos + 15 >= away.ypos) && (away.ypos + 15 >= player.ypos) )   ) || (   (player.xpos + player.width == gameball.xpos) && ( (player.ypos + 15 >= gameball.ypos) && (gameball.ypos + gameball.height >= player.ypos) )   ))) {
            undrawImageDMA(player.ypos, player.xpos, player.width, player.height, fieldscore);
            player.xpos++;
            drawImageDMA(player.ypos, player.xpos, player.width, player.height, pixlplayer);
          }
        }
        if (KEY_JUST_PRESSED(BUTTON_UP, previousButtons, currentButtons) || KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (!((player.ypos <= 0) || (   (player.ypos - 15 == away.ypos) && ( (player.xpos + 20 >= away.xpos) && (away.xpos + 20 >= player.xpos) )   ) || (   (player.ypos - gameball.height == gameball.ypos) && ( (player.xpos + 20 >= gameball.xpos) && (gameball.xpos + gameball.width >= player.xpos) )   ))) {
            undrawImageDMA(player.ypos, player.xpos, player.width, player.height, fieldscore);
            player.ypos--;
            drawImageDMA(player.ypos, player.xpos, player.width, player.height, pixlplayer);
          }
        }
        //Defender movement and collisions
        if (dirLock == cycles) { 
            dirLock = 0; 
            decpos = randint(1, 5);
            cycles = randint(20, 76);
        }
        if (decpos == 1) { //move down
          if (!((away.ypos >= 125) || (   (away.ypos + 15 == player.ypos) && ( (away.xpos + 20 >= player.xpos) && (player.xpos + 20 >= away.xpos) )   ) || (   (away.ypos + 15 == gameball.ypos) && ( (away.xpos + 20 >= gameball.xpos) && (gameball.xpos + gameball.width >= away.xpos) )   ))) {
            undrawImageDMA(away.ypos, away.xpos, away.width, away.height, fieldscore); 
            away.ypos++;
            drawImageDMA(away.ypos, away.xpos, away.width, away.height, pixldefender);
          }
        } else if (decpos == 2) { //move right
            if (!((away.xpos >= 220) || (   (away.xpos + 20 == player.xpos) && ( (away.ypos + 15 >= player.ypos) && (player.ypos + 15 >= away.ypos) )   ) || (   (away.xpos + away.width == gameball.xpos) && ( (away.ypos + 15 >= gameball.ypos) && (gameball.ypos + gameball.height >= away.ypos) )   ))) {
              undrawImageDMA(away.ypos, away.xpos, away.width, away.height, fieldscore);
              away.xpos++; 
              drawImageDMA(away.ypos, away.xpos, away.width, away.height, pixldefender);
            }
        } else if (decpos == 3) { //move left
            if (!((away.xpos <= 0) || (   (away.xpos - 20 == player.xpos) && ( (away.ypos + 15 >= player.ypos) && (player.ypos + 15 >= away.ypos) )   ) || (   (away.xpos - gameball.width == gameball.xpos) && ( (away.ypos + 15 >= gameball.ypos) && (gameball.ypos + gameball.height >= away.ypos) )   ))) {
              undrawImageDMA(away.ypos, away.xpos, away.width, away.height, fieldscore);
              away.xpos--; 
              drawImageDMA(away.ypos, away.xpos, away.width, away.height, pixldefender);
            }
        } else if (decpos == 4) { //move up 
          if (!((away.ypos <= 0) || (   (away.ypos - 15 == player.ypos) && ( (away.xpos + 20 >= player.xpos) && (player.xpos + 20 >= away.xpos) )   ) || (   (away.ypos - gameball.height == gameball.ypos) && ( (away.xpos + 20 >= gameball.xpos) && (gameball.xpos + gameball.width >= away.xpos) )   ))) {
            undrawImageDMA(away.ypos, away.xpos, away.width, away.height, fieldscore); 
            away.ypos--;
            drawImageDMA(away.ypos, away.xpos, away.width, away.height, pixldefender);
          }
        }
        dirLock++;
        //Ball movemement and collisions 
        if ((   (player.ypos + 15 == gameball.ypos) && ( (player.xpos + 20 >= gameball.xpos) && (gameball.xpos + gameball.width >= player.xpos) )   )) {
          if (gameball.ypos < 135) {
            undrawImageDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, fieldscore);
            gameball.ypos++;
            drawRectDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, CYAN);
          } //down
        } else if ((   (player.ypos - gameball.height == gameball.ypos) && ( (player.xpos + 20 >= gameball.xpos) && (gameball.xpos + gameball.width >= player.xpos) )   )) {
          if (gameball.ypos > 0) {
            undrawImageDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, fieldscore);
            gameball.ypos--;
            drawRectDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, CYAN);
          } //up
        } else if ((   (player.xpos - gameball.width == gameball.xpos) && ( (player.ypos + 15 >= gameball.ypos) && (gameball.ypos + gameball.height >= player.ypos) )   )) {
          if (gameball.xpos > 0) {
            undrawImageDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, fieldscore);
            gameball.xpos--;
            drawRectDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, CYAN);
          } //left
        } else if ((   (player.xpos + player.width == gameball.xpos) && ( (player.ypos + 15 >= gameball.ypos) && (gameball.ypos + gameball.height >= player.ypos) )   )) {
          if (gameball.xpos < 235) {
            undrawImageDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, fieldscore);
            gameball.xpos++;
            drawRectDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, CYAN);            
          }
        }//right
        if ((gameball.ypos <= 2) && ((gameball.xpos + gameball.width >= 88) && (156 >= gameball.xpos))) {
          goals++;
          waitForVBlank();
          undrawImageDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, fieldscore);
          undrawImageDMA(away.ypos, away.xpos, away.width, away.height, fieldscore);
          undrawImageDMA(player.ypos, player.xpos, player.width, player.height, fieldscore);
          waitForVBlank(); 
          waitForVBlank(); 
          player.xpos = 110; //starting position
          player.ypos = 125; //starting position
          away.xpos = 130;
          away.ypos =  55;
          gameball.xpos = 117;
          gameball.ypos = 120;
          drawRectDMA(140, 103, 20, 20, BLACK);
          drawChar(146, 114, goals + '0', WHITE);        
        }
        if (goals == 3) {
          state = WIN;
          gameLoop = 0;
        }
        if (((   (away.ypos + 15 == gameball.ypos) && ( (away.xpos + 20 >= gameball.xpos) && (gameball.xpos + gameball.width >= away.xpos) )   ))   ||    ((   (away.ypos - gameball.height == gameball.ypos) && ( (away.xpos + 20 >= gameball.xpos) && (gameball.xpos + gameball.width >= away.xpos) )   ))    ||   ((   (away.xpos - gameball.width == gameball.xpos) && ( (away.ypos + 15 >= gameball.ypos) && (gameball.ypos + gameball.height >= away.ypos) )   ))   ||    ((   (away.xpos + away.width == gameball.xpos) && ( (away.ypos + 15 >= gameball.ypos) && (gameball.ypos + gameball.height >= away.ypos) )   ))) {
          lives--;
          waitForVBlank();
          undrawImageDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, fieldscore);
          undrawImageDMA(away.ypos, away.xpos, away.width, away.height, fieldscore);
          undrawImageDMA(player.ypos, player.xpos, player.width, player.height, fieldscore);
          waitForVBlank(); 
          waitForVBlank(); 
          player.xpos = 110; //starting position
          player.ypos = 125; //starting position
          away.xpos = 130;
          away.ypos =  55;
          gameball.xpos = 117;
          gameball.ypos = 120;
          drawRectDMA(140, 184, 20, 20, BLACK);
          drawChar(146, 186, '0' + lives, WHITE);
        }
        if (lives == 0) {
          state = LOSE; 
          gameLoop = 0;
        }
        if (gameball.ypos == 0 || gameball.xpos == 0) {
          undrawImageDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, fieldscore);
          undrawImageDMA(away.ypos, away.xpos, away.width, away.height, fieldscore);
          undrawImageDMA(player.ypos, player.xpos, player.width, player.height, fieldscore);
          waitForVBlank(); 
          waitForVBlank(); 
          player.xpos = 110; //starting position
          player.ypos = 125; //starting position
          away.xpos = 130;
          away.ypos =  55;
          gameball.xpos = 117;
          gameball.ypos = 120;
        } else if (gameball.ypos + gameball.height == 140 || gameball.xpos + gameball.width == 240) {
          undrawImageDMA(gameball.ypos, gameball.xpos, gameball.width, gameball.height, fieldscore);
          undrawImageDMA(away.ypos, away.xpos, away.width, away.height, fieldscore);
          undrawImageDMA(player.ypos, player.xpos, player.width, player.height, fieldscore);
          waitForVBlank(); 
          waitForVBlank(); 
          player.xpos = 110; //starting position
          player.ypos = 125; //starting position
          away.xpos = 130;
          away.ypos =  55;
          gameball.xpos = 117;
          gameball.ypos = 120;          
        }
        previousButtons = currentButtons; 
      }
        break;
      case INTRO: 
        waitForVBlank();
        drawFullScreenImageDMA(intro);
        if (KEY_JUST_PRESSED(BUTTON_START, previousButtons, currentButtons)) {state = PLAY;}
        break;
      case SPLASH: 
        waitForVBlank(); 
        fillScreenDMA(RED);
        volatile int counter = 0; 
        volatile int xpos = 0; 
        volatile int ypos = 0; 

        for (int i = 0; i < 1000000 ; i++) {
          if (i % 8000 == 0) {
            waitForVBlank();
            drawImageDMA(xpos, ypos, 50, 30, drew); 
            xpos = xpos + 15;
            ypos = ypos + 20;
          }
          counter++;
        }
        state = INTRO; 
        break; 
      case WIN:
        waitForVBlank(); 
        drawFullScreenImageDMA(w);
        // state = ?
        break;
      case LOSE:
      waitForVBlank();
      drawFullScreenImageDMA(l);
        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }
  return 0;
}